services:
  db:
    image: postgres:latest
    container_name: todo_db_spring
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - db_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - db_network
    depends_on:
      - db
volumes:
  data:
    driver: local
networks:
  db_network:
    driver: bridge